"""
Utilities for ASR stage
IMPORTANT: If the Google Cloud Speech API is used, you need to store your credentials as JSON and set an environment variable GOOGLE_APPLICATION_CREDENTIALS pointing to the location of the file!
See: https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries
"""
import io
from os import remove

import soundfile as sf
# Imports the Google Cloud client library
from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types
from tqdm import tqdm

from constants import LANGUAGE_CODES


def transcribe(voice_segments, language, printout=False):
    """
    Transcribe list of voiced segments using Google's STT API
    :param voice_segments: list of util.vad_util.Voice instances
    :param language: language of the voiced segments
    :param printout: str or bool value
        - if a string is supplied, it is interpreted as the path of a file where the translations will be written to
        - if a bool is supplied it is interpreted as flag whether to print the translations to console
    :return:
    """
    progress = tqdm(voice_segments, unit='voice activities')
    for voice in progress:
        transcript = transcribe_audio(voice.audio, voice.rate, language)
        progress.set_description(transcript)
        if printout and type(printout) is bool:
            print(transcript)
        voice.transcript = transcript

    if printout and type(printout) is str:
        print(f'saving ASR-transcripts to {printout}')
        with open(printout, 'w', encoding='utf-8') as f:
            f.writelines('\n'.join(voice.transcript for voice in voice_segments))
    return voice_segments


def transcribe_audio(audio, rate, language):
    """
    Transcribe an audio signal using Google's STT (Google Cloud Speech) API. The implementation uses a temporary file
    holding the PCM_16 encoded audio signal whose contents are sent to Google. This is a hacky solution because librosa
    does not support conversion between WAV subformats (https://librosa.github.io/librosa/ioformats.html).
    It that can be replaced as soon as a solution is found to convert to PCM_16 (raw audio bytes) and call the TTS-API
    directly.

    :param audio: numpy-array with audio signal
    :param rate: sampling rate
    :param language: language of the text spoken in the audio signal
    :return: string holding the transcription generated by Google Cloud Speech
    """
    tmp_file = 'audio.wav.tmp'
    sf.write(tmp_file, audio, rate, format='wav', subtype='PCM_16')
    transcription = transcribe_file(tmp_file, language)
    remove(tmp_file)
    return transcription


def transcribe_file(path, language):
    """
    Translate an PCM_16 encoded audio signal stored in a file using Google's STT API (Google Cloud Speech).
    This implementation should be changed to transcribe audio-bytes directly.
    :param path: path to audio file holding audio bytes
    :param language: language of the text spoken in the audio signal
    :return: string holding the transcription generated by Google Cloud Speech
            or empty string if no transcription was found
    """
    client = speech.SpeechClient()
    with io.open(path, 'rb') as audio_file:
        content = audio_file.read()
        audio = types.RecognitionAudio(content=content)

    language_code = LANGUAGE_CODES[language]
    config = types.RecognitionConfig(
        encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=16000,
        language_code=language_code)

    # Detects speech in the audio file
    response = client.recognize(config, audio)

    if response and response.results:
        return response.results[0].alternatives[0].transcript
    return ''
